"""US ZIP codes to IANA time zones, from about 1.3 KB of tables.

    >>> import ziptz
    >>> ziptz.zone("94110")
    'America/Los_Angeles'
    >>> ziptz.location("10001").key
    'America/New_York'
    >>> ziptz.abbrev("94110", datetime(2026, 7, 15, tzinfo=timezone.utc))
    'PDT'
    >>> ziptz.generic("94110")
    'PT'

Give all five digits and the answer is exact. Three digits -- the prefix alone
-- gets the majority zone for that prefix, which is right for 33,558 of the
33,791 ZIP codes and wrong for the 233 that sit on the losing side of a zone
boundary their prefix has to round the wrong way.

No dependency beyond the standard library, and no I/O of its own: both tables
are string constants in this module, and the first lookup unpacks them into
dicts, so the tables stay small on disk and answering is a hash. `location()`
is the only function that touches the system's time zone database, through
`zoneinfo`.

Data: US Census ZCTA Gazetteer centroids (a US Government work, public domain)
resolved through timezone-boundary-builder (ODbL).

The Go package next door answers identically, ZIP for ZIP; both tables are
generated into the two implementations in one pass by tools/genzips.py, and
must never be edited by hand.

Copyright (c) 2026 cho. MIT licensed; see LICENSE. The tables below contain
information from timezone-boundary-builder, made available under the ODbL, and
from OpenStreetMap, (c) OpenStreetMap contributors; see NOTICE. Dropping this
one file next to whatever imports it is a supported way to use it -- keep this
paragraph when you do, since it is then the only attribution travelling with
the tables.
"""

# Annotations as strings, which is what lets the signatures below be spelled
# the modern way -- `datetime | None` rather than Optional[datetime] -- on the
# 3.9 this library still supports, where that syntax would otherwise raise at
# import time. Nothing here reads its own annotations at runtime.
from __future__ import annotations

from datetime import datetime, timezone as _timezone
from zoneinfo import ZoneInfo

__all__ = [
    "ZipError",
    "zone",
    "location",
    "abbrev",
    "generic",
    "prefix_zone",
    "exact_zone",
]

__version__ = "0.1.1"


class ZipError(ValueError):
    """A ZIP code this table cannot resolve, with a reason fit to print."""


# US ZIP prefixes to time zones, run-length encoded as fixed four-byte records
# "NNNc": the 3-digit prefix a run starts at, then a zone letter from ZONES.
# A run reaches to the next record's prefix, and the last run to 999; "-" marks
# prefixes the Postal Service has not assigned.
RUNS = "000-006R010E055-056E090-100E192-193E213-214E269-270E311-312E324C326E332-333E340-341E343-344E345-346E348-349E350C353-354C374E375-376E380C398E399-400E419-420C425E427C428-430E459-460E463C465E476C478E500C509-510C517-520C529-530C533-534C536-537C552-553C555-556C568-570C576M578-580C586M587C589-590M600C621-622C632-633C642-644C649-650C659-660C663-664C682-683C691M692C693M694-700C702-703C709-710C715-716C732-734C742-743C771-772C799M817-820M835P836M838P839-840M842-843M848-850Z854-855Z858-859Z861-863Z865M866-870M872-873M876-877M885-890P892-893P896-897P899-900P901-902P909-910P929-930P938-939P942-943P962-967H969G970P979M980P987-988P995A"  # zip-runs: generated by tools/genzips.py

# The one-letter codes in RUNS and EXCEPTIONS, as real zone names. Phoenix is
# separate from Denver because Arizona does not observe daylight saving, and
# Adak from Anchorage because the western Aleutians run an hour further behind.
ZONES = {
    "A": "America/Anchorage",
    "C": "America/Chicago",
    "D": "America/Adak",
    "E": "America/New_York",
    "G": "Pacific/Guam",
    "H": "Pacific/Honolulu",
    "M": "America/Denver",
    "P": "America/Los_Angeles",
    "R": "America/Puerto_Rico",
    "S": "Pacific/Pago_Pago",
    "Z": "America/Phoenix",
}

# Each zone's name with the daylight-saving question left out: "PT" covers
# both PST and PDT, and is what to print when the instant is not decided yet or
# does not matter. CLDR calls this the generic non-location short format, and
# the pair abbrev() returns the specific one.
#
# A zone that never shifts has no pair to generalise over, so its generic name
# is simply its abbreviation -- Phoenix is MST in January and in July, and MST
# generically. The tests hold every entry here to that rule.
#
# One line per entry, in the same order as ziptz.go's, so the two can be
# compared without parsing either.
GENERIC = {
    "America/Adak": "HAT",
    "America/Anchorage": "AKT",
    "America/Chicago": "CT",
    "America/Denver": "MT",
    "America/Los_Angeles": "PT",
    "America/New_York": "ET",
    "America/Phoenix": "MST",
    "America/Puerto_Rico": "AST",
    "Pacific/Guam": "ChST",
    "Pacific/Honolulu": "HST",
    "Pacific/Pago_Pago": "SST",
}

# The ZIPs a 3-digit prefix gets wrong. A prefix that straddles a zone boundary
# has to round to one side, so every ZIP on the losing side is an hour or more
# out; these records name each of them exactly. Consulted only when all five
# digits were given, since three cannot say which ZIP is meant.
#
# A record is "PPPcNN" -- prefix, zone letter from ZONES, and how many
# two-digit suffixes follow -- then that many suffixes, ascending:
#
#     373C38 01 02 07 ...        (spaces for clarity only)
#
# Writing the prefix once per group rather than once per ZIP is what keeps this
# smaller than a flat table of five-digit records. The stride varies, so this is
# a short forward scan rather than a binary search -- there are only thirty-odd
# groups.
#
# Sourced from the same Census ZCTA centroids as RUNS, so it covers every ZIP
# that has a ZCTA; PO-box and single-building ZIPs have none, and still fall
# back to their prefix.
EXCEPTIONS = "324E0156368E06546367697077373E380203070809101112151617212223252629313233363741435051535461626369707379818591374C0119377C0123401C1311151940434445465270717678426C03022942427E12011618243233404858768488465C03313234475C1614152023253137505152747677798688479C082243485163647778498C230102121521313447485258637073747677818687929396499C12020311152027353847596869575M1032374347515253677477576C0431324648585M052933626469586C023138588M0138677M06333541586162678M0436577879690M082123273033374145691C18012023303235384243515763656667697071692M0411161819798M1021353637383947495153835M0422424749860M1303162031333435404445475354865Z0102967S0199979P03040507995D024647"  # zip-exceptions: generated by tools/genzips.py


def prefix_zone(p3: str) -> str:
    """The zone name for a 3-digit ZIP prefix, or "" if unassigned.

    The argument is checked before it is used, because the table this reads
    was until recently searched rather than indexed, and that search found the
    last record sorting at or below its argument -- so anything that is not a
    prefix still found *something*. "99" sorted below "990" and answered Los
    Angeles, "9999" above "995" and answered Anchorage, and "94 " below "941"
    and answered Los Angeles for a space. Go checked the length and this did
    not, so the two ports disagreed on a public function; neither checked the
    digits, so both were wrong about "94 " together. The sweep sees neither:
    every token it asks about is well formed by construction.

    isdigit() alone would be wrong here -- it is true of "١" and "１"
    as well as "1", and the two ports have to accept the same strings -- so it
    is paired with isascii(), the way env_whole does it in the clock.
    """
    if len(p3) != 3 or not (p3.isascii() and p3.isdigit()):
        return ""
    return _prefix_index().get(p3, "")


# The run table, unpacked into a dictionary on first use; see _exact_index for
# the argument, which is the same one. 896 assigned prefixes, and the binary
# search this replaces cost more than the length check guarding it.
_prefix_cache = None


def _prefix_index() -> dict[str, str]:
    """RUNS as {prefix: zone name}, built once.

    Unassigned prefixes are left out rather than stored empty, so a miss and an
    unassigned prefix both answer "" through .get() without distinguishing
    them -- which is what the binary search did too.
    """
    global _prefix_cache
    if _prefix_cache is None:
        index: dict[str, str] = {}
        records = len(RUNS) // 4
        for r in range(records):
            start = int(RUNS[r * 4 : r * 4 + 3])
            # a run reaches to the next record's prefix, and the last one to 999
            end = int(RUNS[(r + 1) * 4 : (r + 1) * 4 + 3]) if r + 1 < records else 1000
            name = ZONES.get(RUNS[r * 4 + 3], "")
            if name:
                for p in range(start, end):
                    index[f"{p:03d}"] = name
        _prefix_cache = index
    return _prefix_cache


# The exception table, unpacked into a dictionary on first use. None until
# something asks, so a program that never resolves a ZIP never builds it.
#
# The table is the compact thing that ships; this is the fast thing to ask.
# Walking it per lookup meant slicing a group header and parsing a count for
# every group before the answer -- about thirty of each in the worst case, and
# 71% of what zone() cost. Unpacked, it is 233 entries, well under a tenth of a
# millisecond to build and about 20 KB to hold, and a lookup is one hash.
#
# Laziness is the whole argument for a dict here rather than a dict in the
# source: the shipped tables stay 1.3 KB, which is what makes vendoring one
# file reasonable, and only a caller who actually looks a ZIP up pays for the
# index. Two threads racing to build it both build the same thing and one wins;
# there is nothing to lock.
_exact_cache = None


def _exact_index() -> dict[str, str]:
    """EXCEPTIONS as {zip5: zone name}, built once."""
    global _exact_cache
    if _exact_cache is None:
        index: dict[str, str] = {}
        i = 0
        while i < len(EXCEPTIONS):
            group = EXCEPTIONS[i : i + 3]
            zone_name = ZONES.get(EXCEPTIONS[i + 3], "")
            count = int(EXCEPTIONS[i + 4 : i + 6])
            body = i + 6
            for k in range(count):
                index[group + EXCEPTIONS[body + k * 2 : body + k * 2 + 2]] = zone_name
            i = body + count * 2
        _exact_cache = index
    return _exact_cache


def exact_zone(zip5: str) -> str:
    """The zone name for one exact 5-digit ZIP, or "" if its prefix gets it right."""
    if not isinstance(zip5, str) or len(zip5) != 5:
        return ""
    return _exact_index().get(zip5, "")


# How much of a rejected token an error is willing to quote, and what it will
# quote. The text is written to be printed as-is, which means it can end up in
# a log line, so a token arriving from a form or a socket cannot be echoed
# whole: 100,000 digits made a 100,065-character error, and a newline in the
# middle made an error that was two log lines, the second of them attacker-
# written.
#
# Anything outside printable ASCII becomes "?" rather than an escape, because
# Go's %q and Python's !r disagree about non-ASCII and this has to be one
# string in both. Counted in characters, not bytes, for the same reason.
_shown = 20


def _show(token: str) -> str:
    """A token as an error may quote it: printable ASCII, 20 characters."""
    out = []
    for i, ch in enumerate(token):
        if i == _shown:
            out.append("...")
            break
        out.append(ch if " " <= ch <= "~" else "?")
    return "".join(out)


def zone(token: str) -> str:
    """The IANA zone name for a 3- or 5-digit US ZIP, e.g. "America/Denver".

    Raises ZipError if the token is not a ZIP code, or names a prefix the
    Postal Service has not assigned.

    isinstance is checked because bytes would otherwise pass every test here --
    b"94110" has a length, isascii() and isdigit() -- and then miss both
    indexes, so a caller who forgot to decode was told that San Francisco's
    prefix does not exist, with b'941' in the message. Go cannot express the
    mistake, so nothing but this catches it.
    """
    if not isinstance(token, str) or len(token) not in (3, 5) or not (
        token.isascii() and token.isdigit()
    ):
        # repr for a non-str, so that b"94110" is visibly bytes rather than
        # silently printing as though it were the string. Through _show either
        # way: a repr is as unbounded as the thing it describes.
        shown = _show(token if isinstance(token, str) else repr(token))
        raise ZipError(
            f'"{shown}" is not a US ZIP code; give all five digits, or the first three'
        )
    prefix = token[:3]
    # an exact ZIP beats its prefix's majority; three digits have only the
    # majority to go on
    name = (exact_zone(token) if len(token) == 5 else "") or prefix_zone(prefix)
    if not name:
        raise ZipError(f"no US time zone is recorded for ZIP codes starting {prefix}")
    return name


def location(token: str) -> ZoneInfo:
    """zone(), loaded from the system's time zone database as a ZoneInfo.

    Raises ZipError for the same reasons as zone(), and additionally when the
    name is one this system's database does not carry.
    """
    name = zone(token)
    try:
        return ZoneInfo(name)
    except Exception:
        raise ZipError(
            f"ZIP {token[:3]} means {name}, which this system's time zone database lacks"
        ) from None


def abbrev(token: str, at: datetime | None = None) -> str:
    """The zone's abbreviation at one instant: "PST" in January, "PDT" in July.

    The instant decides it, so pass the one you mean; `at` defaults to now, and
    an aware datetime is expected -- a naive one is read as system local time,
    the way astimezone() reads it. Go has no default and takes the instant
    always.

    The abbreviation comes from the system's time zone database rather than
    from a table here, so it stays right through rule changes, and needs that
    database present -- unlike generic(), which does not.

    Raises ZipError for the same reasons as location().
    """
    tz = location(token)
    if at is None:
        at = datetime.now(_timezone.utc)
    # tzname() is Optional on tzinfo in general, and a type checker reading
    # that signature cannot know this one is always a ZoneInfo -- which names
    # every zone ZONES can hold, so None is unreachable here. Spelt as a
    # fallback rather than an assert: a library that raises where it could
    # answer is worse, and an empty abbreviation would be visibly wrong on the
    # face of a clock if the unreachable ever happened.
    return at.astimezone(tz).tzname() or ""


def generic(token: str) -> str:
    """The zone's name with daylight saving left out: "PT" for Los Angeles.

    What to print when the instant is not decided yet or does not matter. A
    zone that never shifts gives its one abbreviation instead: Phoenix is
    "MST", Honolulu "HST".

    Reads no time zone database, so this answers on a system that has none.
    Raises ZipError for the same reasons as zone().
    """
    return GENERIC[zone(token)]
