// Package ziptz resolves US ZIP codes to IANA time zones from about 1.3 KB of
// tables.
//
//	name, err := ziptz.Zone("94110")            // "America/Los_Angeles"
//	loc, err := ziptz.Location("10001")
//	abb, err := ziptz.Abbrev("94110", when)     // "PST" in January, "PDT" in July
//	gen, err := ziptz.Generic("94110")          // "PT", whatever the date
//
// Give all five digits and the answer is exact. Three digits -- the prefix
// alone -- gets the majority zone for that prefix, which is right for 33,558 of
// the 33,791 ZIP codes and wrong for the 233 that sit on the losing side of a
// zone boundary their prefix has to round the wrong way.
//
// No dependency beyond the standard library, and no I/O of its own: both tables
// are string constants in this package, and the first lookup unpacks them into
// maps, so the tables stay small on disk and answering is a hash. [Location] is
// the only function that touches the system's time zone database, through
// [time.LoadLocation].
//
// Data: US Census ZCTA Gazetteer centroids (a US Government work, public
// domain) resolved through timezone-boundary-builder (ODbL).
//
// The Python module next door answers identically, ZIP for ZIP; both tables are
// generated into the two implementations in one pass by tools/genzips.py, and
// must never be edited by hand.
//
// Copyright (c) 2026 cho. MIT licensed; see LICENSE. The tables below contain
// information from timezone-boundary-builder, made available under the ODbL,
// and from OpenStreetMap, (c) OpenStreetMap contributors; see NOTICE. Dropping
// this one file into a package of your own is a supported way to use it -- keep
// this paragraph when you do, since it is then the only attribution travelling
// with the tables.
package ziptz

//go:generate python3 tools/genzips.py

import (
	"fmt"
	"strings"
	"sync"
	"time"
)

// Version is the release this source belongs to; the Python module carries the
// same string.
const Version = "0.1.0"

// runs maps US ZIP prefixes to time zones, run-length encoded as fixed
// four-byte records "NNNc": the 3-digit prefix a run starts at, then a zone
// letter from zones. A run reaches to the next record's prefix, and the last
// run to 999; "-" marks prefixes the Postal Service has not assigned.
const runs = "000-006R010E055-056E090-100E192-193E213-214E269-270E311-312E324C326E332-333E340-341E343-344E345-346E348-349E350C353-354C374E375-376E380C398E399-400E419-420C425E427C428-430E459-460E463C465E476C478E500C509-510C517-520C529-530C533-534C536-537C552-553C555-556C568-570C576M578-580C586M587C589-590M600C621-622C632-633C642-644C649-650C659-660C663-664C682-683C691M692C693M694-700C702-703C709-710C715-716C732-734C742-743C771-772C799M817-820M835P836M838P839-840M842-843M848-850Z854-855Z858-859Z861-863Z865M866-870M872-873M876-877M885-890P892-893P896-897P899-900P901-902P909-910P929-930P938-939P942-943P962-967H969G970P979M980P987-988P995A" // zip-runs: generated by tools/genzips.py

// zones maps the one-letter codes in runs and exceptions to real zone names.
// Phoenix is separate from Denver because Arizona does not observe daylight
// saving, and Adak from Anchorage because the western Aleutians run an hour
// further behind.
var zones = map[byte]string{
	'A': "America/Anchorage",
	'C': "America/Chicago",
	'D': "America/Adak",
	'E': "America/New_York",
	'G': "Pacific/Guam",
	'H': "Pacific/Honolulu",
	'M': "America/Denver",
	'P': "America/Los_Angeles",
	'R': "America/Puerto_Rico",
	'S': "Pacific/Pago_Pago",
	'Z': "America/Phoenix",
}

// generic is each zone's name with the daylight-saving question left out:
// "PT" covers both PST and PDT, and is what to print when the instant is not
// decided yet or does not matter. CLDR calls this the generic non-location
// short format, and the pair Abbrev returns the specific one.
//
// A zone that never shifts has no pair to generalise over, so its generic name
// is simply its abbreviation -- Phoenix is MST in January and in July, and MST
// generically. The tests hold every entry here to that rule.
//
// One line per entry, in the same order as ziptz.py's, so the two can be
// compared without parsing either.
var generic = map[string]string{
	"America/Adak":        "HAT",
	"America/Anchorage":   "AKT",
	"America/Chicago":     "CT",
	"America/Denver":      "MT",
	"America/Los_Angeles": "PT",
	"America/New_York":    "ET",
	"America/Phoenix":     "MST",
	"America/Puerto_Rico": "AST",
	"Pacific/Guam":        "ChST",
	"Pacific/Honolulu":    "HST",
	"Pacific/Pago_Pago":   "SST",
}

// exceptions are the ZIPs a 3-digit prefix gets wrong. A prefix that straddles
// a zone boundary has to round to one side, so every ZIP on the losing side is
// an hour or more out; these records name each of them exactly. Consulted only
// when all five digits were given, since three cannot say which ZIP is meant.
//
// A record is "PPPcNN" -- prefix, zone letter from zones, and how many
// two-digit suffixes follow -- then that many suffixes, ascending:
//
//	373C38 01 02 07 ...        (spaces for clarity only)
//
// Writing the prefix once per group rather than once per ZIP is what keeps this
// smaller than a flat table of five-digit records. The stride varies, so this
// is a short forward scan rather than a binary search -- there are only
// thirty-odd groups.
//
// Sourced from the same Census ZCTA centroids as runs, so it covers every ZIP
// that has a ZCTA; PO-box and single-building ZIPs have none, and still fall
// back to their prefix.
const exceptions = "324E0156368E06546367697077373E380203070809101112151617212223252629313233363741435051535461626369707379818591374C0119377C0123401C1311151940434445465270717678426C03022942427E12011618243233404858768488465C03313234475C1614152023253137505152747677798688479C082243485163647778498C230102121521313447485258637073747677818687929396499C12020311152027353847596869575M1032374347515253677477576C0431324648585M052933626469586C023138588M0138677M06333541586162678M0436577879690M082123273033374145691C18012023303235384243515763656667697071692M0411161819798M1021353637383947495153835M0422424749860M1303162031333435404445475354865Z0102967S0199979P03040507995D024647" // zip-exceptions: generated by tools/genzips.py

// PrefixZone is the zone name for a 3-digit ZIP prefix, "" if unassigned.
//
// The argument is checked before it is used, because the table this reads was
// until recently searched rather than indexed, and that search found the last
// record sorting at or below its argument -- so anything that is not a prefix
// still found something. "99" sorted below "990", "9999" above "995", and
// "94 " below "941", which answered Los Angeles for a space. Python checked
// none of this and disagreed here; neither side checked the digits, so both
// were wrong about "94 " together. The sweep sees neither, since every token
// it asks about is well formed by construction.
func PrefixZone(p3 string) string {
	if len(p3) != 3 {
		return ""
	}
	for i := 0; i < 3; i++ {
		if p3[i] < '0' || p3[i] > '9' {
			return ""
		}
	}
	return prefixZones()[p3]
}

// prefixOnce guards the run index; see exactZones for the argument, which is
// the same one. 896 assigned prefixes, and the binary search this replaces
// cost more than the checks guarding it.
var (
	prefixOnce  sync.Once
	prefixIndex map[string]string
)

// prefixZones is the run table unpacked into a map, built once. Unassigned
// prefixes are left out rather than stored empty, so a miss and an unassigned
// prefix both answer "" without distinguishing them -- which is what the
// binary search did too.
func prefixZones() map[string]string {
	prefixOnce.Do(func() {
		index := make(map[string]string, 1024)
		records := len(runs) / 4
		for r := 0; r < records; r++ {
			start := atoi3(runs[r*4 : r*4+3])
			// a run reaches to the next record's prefix, and the last one to 999
			end := 1000
			if r+1 < records {
				end = atoi3(runs[(r+1)*4 : (r+1)*4+3])
			}
			name := zones[runs[r*4+3]]
			if name == "" {
				continue
			}
			for p := start; p < end; p++ {
				index[string([]byte{byte('0' + p/100), byte('0' + p/10%10), byte('0' + p%10)})] = name
			}
		}
		prefixIndex = index
	})
	return prefixIndex
}

// atoi3 reads exactly three ASCII digits, which is all the run table holds.
func atoi3(s string) int {
	return int(s[0]-'0')*100 + int(s[1]-'0')*10 + int(s[2]-'0')
}

// exactOnce guards the exception index, built the first time anything asks for
// an exact ZIP. A program that never resolves one never builds it.
var (
	exactOnce  sync.Once
	exactIndex map[string]string
)

// exactZones is the exception table unpacked into a map, built once.
//
// The table is the compact thing that ships; this is the fast thing to ask.
// Walking it per lookup meant slicing a group header and parsing a count for
// every group before the answer -- about thirty of each in the worst case, and
// the majority of what Zone cost. Unpacked it is 233 entries, and a lookup is
// one hash.
//
// Laziness is the whole argument for building this rather than writing a map
// into the source: the shipped tables stay 1.3 KB, which is what makes
// vendoring one file reasonable, and only a caller who looks a ZIP up pays.
func exactZones() map[string]string {
	exactOnce.Do(func() {
		index := make(map[string]string, 256)
		for i := 0; i < len(exceptions); {
			group := exceptions[i : i+3]
			name := zones[exceptions[i+3]]
			count := int(exceptions[i+4]-'0')*10 + int(exceptions[i+5]-'0')
			body := i + 6
			for k := 0; k < count; k++ {
				index[group+exceptions[body+k*2:body+k*2+2]] = name
			}
			i = body + count*2
		}
		exactIndex = index
	})
	return exactIndex
}

// ExactZone is the zone name for one exact 5-digit ZIP, or "" if its prefix
// gets it right.
func ExactZone(zip5 string) string {
	if len(zip5) != 5 {
		return ""
	}
	return exactZones()[zip5]
}

// shown is how much of a rejected token an error is willing to quote, and
// show is what it quotes. The text is written to be printed as-is, which means
// it can end up in a log line, so a token arriving from a form or a socket
// cannot be echoed whole: 100,000 digits made a 100,065-character error, and a
// newline in the middle made an error that was two log lines, the second of
// them attacker-written.
//
// Anything outside printable ASCII becomes "?" rather than an escape, because
// %q and Python's !r disagree about non-ASCII and this has to be one string in
// both. Ranged over runes, not bytes, for the same reason.
const shown = 20

func show(token string) string {
	var b strings.Builder
	i := 0
	for _, r := range token {
		if i == shown {
			b.WriteString("...")
			break
		}
		if r >= ' ' && r <= '~' {
			b.WriteRune(r)
		} else {
			b.WriteByte('?')
		}
		i++
	}
	return b.String()
}

// Zone is the IANA zone name for a 3- or 5-digit US ZIP, e.g. "America/Denver".
// It reports an error if the token is not a ZIP code, or names a prefix the
// Postal Service has not assigned.
func Zone(token string) (string, error) {
	if !isZIP(token) {
		return "", fmt.Errorf(
			"\"%s\" is not a US ZIP code; give all five digits, or the first three",
			show(token))
	}
	prefix := token[:3]
	// an exact ZIP beats its prefix's majority; three digits have only the
	// majority to go on
	name := ""
	if len(token) == 5 {
		name = ExactZone(token)
	}
	if name == "" {
		name = PrefixZone(prefix)
	}
	if name == "" {
		return "", fmt.Errorf("no US time zone is recorded for ZIP codes starting %s", prefix)
	}
	return name, nil
}

// Location is Zone, loaded from the system's time zone database. It reports an
// error for the same reasons as Zone, and additionally when the name is one
// this system's database does not carry.
func Location(token string) (*time.Location, error) {
	name, err := Zone(token)
	if err != nil {
		return nil, err
	}
	loc, err := time.LoadLocation(name)
	if err != nil {
		return nil, fmt.Errorf("ZIP %s means %s, which this system's time zone database lacks",
			token[:3], name)
	}
	return loc, nil
}

// Abbrev is the zone's abbreviation at one instant: "PST" in January, "PDT" in
// July. The instant decides it, so there is no default; Python's abbrev()
// takes the same argument and defaults it to now.
//
// The abbreviation comes from the system's time zone database rather than from
// a table here, so it stays right through rule changes, and needs that
// database present -- unlike Generic, which does not.
//
// It reports an error for the same reasons as Location.
func Abbrev(token string, at time.Time) (string, error) {
	loc, err := Location(token)
	if err != nil {
		return "", err
	}
	return at.In(loc).Format("MST"), nil
}

// Generic is the zone's name with daylight saving left out: "PT" for Los
// Angeles. What to print when the instant is not decided yet or does not
// matter. A zone that never shifts gives its one abbreviation instead: Phoenix
// is "MST", Honolulu "HST".
//
// It reads no time zone database, so this answers on a system that has none,
// and reports an error for the same reasons as Zone.
func Generic(token string) (string, error) {
	name, err := Zone(token)
	if err != nil {
		return "", err
	}
	return generic[name], nil
}

// isZIP reports whether the token is three or five ASCII digits.
func isZIP(token string) bool {
	if len(token) != 3 && len(token) != 5 {
		return false
	}
	for i := 0; i < len(token); i++ {
		if token[i] < '0' || token[i] > '9' {
			return false
		}
	}
	return true
}
