"""US ZIP codes to IANA time zones, from about 1.3 KB of tables.

    >>> import ziptz
    >>> ziptz.zone("94110")
    'America/Los_Angeles'
    >>> ziptz.location("10001").key
    'America/New_York'
    >>> ziptz.abbrev("94110", datetime(2026, 7, 15, tzinfo=timezone.utc))
    'PDT'
    >>> ziptz.generic("94110")
    'PT'

Give all five digits and the answer is exact. Three digits -- the prefix alone
-- gets the majority zone for that prefix, which is right for 33,558 of the
33,791 ZIP codes and wrong for the 233 that sit on the losing side of a zone
boundary their prefix has to round the wrong way.

No dependency beyond the standard library, and no I/O of its own: both tables
are string constants in this module, so a lookup is a binary search and a short
scan. `location()` is the only function that touches the system's time zone
database, through `zoneinfo`.

Data: US Census ZCTA Gazetteer centroids (a US Government work, public domain)
resolved through timezone-boundary-builder (ODbL).

The Go package next door answers identically, ZIP for ZIP; both tables are
generated into the two implementations in one pass by tools/genzips.py, and
must never be edited by hand.
"""

# Annotations as strings, which is what lets the signatures below be spelled
# the modern way -- `datetime | None` rather than Optional[datetime] -- on the
# 3.9 this library still supports, where that syntax would otherwise raise at
# import time. Nothing here reads its own annotations at runtime.
from __future__ import annotations

from datetime import datetime, timezone as _timezone
from zoneinfo import ZoneInfo

__all__ = [
    "ZipError",
    "zone",
    "location",
    "abbrev",
    "generic",
    "prefix_zone",
    "exact_zone",
]

__version__ = "0.1.0"


class ZipError(ValueError):
    """A ZIP code this table cannot resolve, with a reason fit to print."""


# US ZIP prefixes to time zones, run-length encoded as fixed four-byte records
# "NNNc": the 3-digit prefix a run starts at, then a zone letter from ZONES.
# A run reaches to the next record's prefix, and the last run to 999; "-" marks
# prefixes the Postal Service has not assigned.
RUNS = "000-006R010E055-056E090-100E192-193E213-214E269-270E311-312E324C326E332-333E340-341E343-344E345-346E348-349E350C353-354C374E375-376E380C398E399-400E419-420C425E427C428-430E459-460E463C465E476C478E500C509-510C517-520C529-530C533-534C536-537C552-553C555-556C568-570C576M578-580C586M587C589-590M600C621-622C632-633C642-644C649-650C659-660C663-664C682-683C691M692C693M694-700C702-703C709-710C715-716C732-734C742-743C771-772C799M817-820M835P836M838P839-840M842-843M848-850Z854-855Z858-859Z861-863Z865M866-870M872-873M876-877M885-890P892-893P896-897P899-900P901-902P909-910P929-930P938-939P942-943P962-967H969G970P979M980P987-988P995A"  # zip-runs: generated by tools/genzips.py

# The one-letter codes in RUNS and EXCEPTIONS, as real zone names. Phoenix is
# separate from Denver because Arizona does not observe daylight saving, and
# Adak from Anchorage because the western Aleutians run an hour further behind.
ZONES = {
    "A": "America/Anchorage",
    "C": "America/Chicago",
    "D": "America/Adak",
    "E": "America/New_York",
    "G": "Pacific/Guam",
    "H": "Pacific/Honolulu",
    "M": "America/Denver",
    "P": "America/Los_Angeles",
    "R": "America/Puerto_Rico",
    "S": "Pacific/Pago_Pago",
    "Z": "America/Phoenix",
}

# Each zone's name with the daylight-saving question left out: "PT" covers
# both PST and PDT, and is what to print when the instant is not decided yet or
# does not matter. CLDR calls this the generic non-location short format, and
# the pair abbrev() returns the specific one.
#
# A zone that never shifts has no pair to generalise over, so its generic name
# is simply its abbreviation -- Phoenix is MST in January and in July, and MST
# generically. The tests hold every entry here to that rule.
#
# One line per entry, in the same order as ziptz.go's, so the two can be
# compared without parsing either.
GENERIC = {
    "America/Adak": "HAT",
    "America/Anchorage": "AKT",
    "America/Chicago": "CT",
    "America/Denver": "MT",
    "America/Los_Angeles": "PT",
    "America/New_York": "ET",
    "America/Phoenix": "MST",
    "America/Puerto_Rico": "AST",
    "Pacific/Guam": "ChST",
    "Pacific/Honolulu": "HST",
    "Pacific/Pago_Pago": "SST",
}

# The ZIPs a 3-digit prefix gets wrong. A prefix that straddles a zone boundary
# has to round to one side, so every ZIP on the losing side is an hour or more
# out; these records name each of them exactly. Consulted only when all five
# digits were given, since three cannot say which ZIP is meant.
#
# A record is "PPPcNN" -- prefix, zone letter from ZONES, and how many
# two-digit suffixes follow -- then that many suffixes, ascending:
#
#     373C38 01 02 07 ...        (spaces for clarity only)
#
# Writing the prefix once per group rather than once per ZIP is what keeps this
# smaller than a flat table of five-digit records. The stride varies, so this is
# a short forward scan rather than a binary search -- there are only thirty-odd
# groups.
#
# Sourced from the same Census ZCTA centroids as RUNS, so it covers every ZIP
# that has a ZCTA; PO-box and single-building ZIPs have none, and still fall
# back to their prefix.
EXCEPTIONS = "324E0156368E06546367697077373E380203070809101112151617212223252629313233363741435051535461626369707379818591374C0119377C0123401C1311151940434445465270717678426C03022942427E12011618243233404858768488465C03313234475C1614152023253137505152747677798688479C082243485163647778498C230102121521313447485258637073747677818687929396499C12020311152027353847596869575M1032374347515253677477576C0431324648585M052933626469586C023138588M0138677M06333541586162678M0436577879690M082123273033374145691C18012023303235384243515763656667697071692M0411161819798M1021353637383947495153835M0422424749860M1303162031333435404445475354865Z0102967S0199979P03040507995D024647"  # zip-exceptions: generated by tools/genzips.py


def prefix_zone(p3: str) -> str:
    """The zone name for a 3-digit ZIP prefix, or "" if unassigned.

    Binary search over fixed-width records; the string comparison is exact
    because zero-padded 3-digit decimals sort lexicographically the way they
    sort numerically, so no integer parsing is involved on either side.
    """
    lo, hi, hit = 0, len(RUNS) // 4 - 1, -1
    while lo <= hi:
        mid = (lo + hi) // 2
        if RUNS[mid * 4 : mid * 4 + 3] <= p3:
            hit = mid
            lo = mid + 1
        else:
            hi = mid - 1
    if hit < 0:
        return ""
    return ZONES.get(RUNS[hit * 4 + 3], "")


def exact_zone(zip5: str) -> str:
    """The zone name for one exact 5-digit ZIP, or "" if its prefix gets it right."""
    prefix, suffix = zip5[:3], zip5[3:]
    i = 0
    while i < len(EXCEPTIONS):
        group = EXCEPTIONS[i : i + 3]
        letter = EXCEPTIONS[i + 3]
        count = int(EXCEPTIONS[i + 4 : i + 6])
        body = i + 6
        if group == prefix:
            for k in range(count):
                if EXCEPTIONS[body + k * 2 : body + k * 2 + 2] == suffix:
                    return ZONES.get(letter, "")
            # fall through: a prefix may own more than one group
        elif group > prefix:
            break  # records are sorted, so no later group can match
        i = body + count * 2
    return ""


def zone(token: str) -> str:
    """The IANA zone name for a 3- or 5-digit US ZIP, e.g. "America/Denver".

    Raises ZipError if the token is not a ZIP code, or names a prefix the
    Postal Service has not assigned.
    """
    if len(token) not in (3, 5) or not (token.isascii() and token.isdigit()):
        raise ZipError(
            f'"{token}" is not a US ZIP code; give all five digits, or the first three'
        )
    prefix = token[:3]
    # an exact ZIP beats its prefix's majority; three digits have only the
    # majority to go on
    name = (exact_zone(token) if len(token) == 5 else "") or prefix_zone(prefix)
    if not name:
        raise ZipError(f"no US time zone is recorded for ZIP codes starting {prefix}")
    return name


def location(token: str) -> ZoneInfo:
    """zone(), loaded from the system's time zone database as a ZoneInfo.

    Raises ZipError for the same reasons as zone(), and additionally when the
    name is one this system's database does not carry.
    """
    name = zone(token)
    try:
        return ZoneInfo(name)
    except Exception:
        raise ZipError(
            f"ZIP {token[:3]} means {name}, which this system's time zone database lacks"
        ) from None


def abbrev(token: str, at: datetime | None = None) -> str:
    """The zone's abbreviation at one instant: "PST" in January, "PDT" in July.

    The instant decides it, so pass the one you mean; `at` defaults to now, and
    an aware datetime is expected -- a naive one is read as system local time,
    the way astimezone() reads it. Go has no default and takes the instant
    always.

    The abbreviation comes from the system's time zone database rather than
    from a table here, so it stays right through rule changes, and needs that
    database present -- unlike generic(), which does not.

    Raises ZipError for the same reasons as location().
    """
    tz = location(token)
    if at is None:
        at = datetime.now(_timezone.utc)
    return at.astimezone(tz).tzname()


def generic(token: str) -> str:
    """The zone's name with daylight saving left out: "PT" for Los Angeles.

    What to print when the instant is not decided yet or does not matter. A
    zone that never shifts gives its one abbreviation instead: Phoenix is
    "MST", Honolulu "HST".

    Reads no time zone database, so this answers on a system that has none.
    Raises ZipError for the same reasons as zone().
    """
    return GENERIC[zone(token)]
